### ISSUE TITLE
[Regression] #434 introduced race condition in initialization of client context

### ISSUE THREAD

**Issue by bsless** [http-kit/http-kit#456]
Hi,
Before #434 the SSL context was initialized once during class initialization. The client context is initialized during `trustAnybody`.
If `trustAnybody` is called in parallel before initialization finishes, it can override the clientContextImpl initialization and throw
`SSLContextImpl is not initialized`.
In short, `trustAnybody` is not thread safe.
Stacktrace:
```
java.lang.IllegalStateException: SSLContextImpl is not initialized
at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:191)
at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:329)
at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:26)
at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
at org.httpkit.client$request.invokeStatic(client.clj:242)
```

**Comment by bsless** [comment]
Resolved by 816d308ba590bc4d557abbc12cb276ad9ed5977c

**Comment by itaysabato** [comment]
Using `v2.5.1` and this bug persists - looked in the jar I got from clojars and the fix is simply not there!
I think the latest release needs to be republished.

**Comment by ptaoussanis** [comment]
@itaysabato Hi Itay,

`v2.5.1` was published [Jan 14](https://github.com/http-kit/http-kit/releases/tag/v2.5.1), and this PR merged Feb 6. It will be included in the next release. You can always check the [release notes](https://github.com/http-kit/http-kit/releases) to see what changes are included in each release.

Thanks

**Comment by itaysabato** [comment]
@ptaoussanis Right, sorry. I now see I misread the release notes.
However, this is a big production problem for us - when is the next version expected to be released?

**Comment by bsless** [comment]
@itaysabato unless there's something you must have in later versions, you can use `2.4.0` for now. This is what I did at work until the fix gets released

**Comment by itaysabato** [comment]
@bsless Thanks, we're trying that.
Would appreciate a ping here once this gets released.

**Comment by borkdude** [comment]
@itaysabato You can subscribe to release notifications on Github.

**Comment by bsless** [comment]
@itaysabato 2.5.2 released

**Comment by itaysabato** [comment]
Thanks for the ping!
Updated to 2.5.3 - so far so good.
